---
- name: Install basic tools
  package:
    name:
      - vim
      - traceroute
      - curl
      - wget
      - tcpdump
      - tree
      - net-tools
      - bash-completion
    state: present

- name: Install VMware tools
  package:
    name:
      - open-vm-tools
    state: present
  when:
    - ansible_virtualization_type == "vmware" and ansible_virtualization_role == "guest"
    