---
- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when:
    - ansible_os_family == "RedHat"

- name: Restart ssh
  service:
    name: sshd
    state: restarted
  when:
    - ansible_os_family == "Debian"
